# Generated by Django 2.0.2 on 2018-06-27 14:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20180627_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 27, 14, 41, 25, 351906, tzinfo=utc)),
        ),
    ]
